CREATE SCHEMA IF NOT EXISTS PAYTRACKER;
SET SCHEMA PAYTRACKER;
CREATE TABLE PAYER (
                       ID INT AUTO_INCREMENT PRIMARY KEY,
                       NAME VARCHAR(15) NOT NULL
);

CREATE TABLE CURRENCY(
                         ID INT AUTO_INCREMENT PRIMARY KEY,
                         CCY_CD VARCHAR(3) NOT NULL
);

CREATE TABLE PAYMENT (
                         ID INT AUTO_INCREMENT PRIMARY KEY,
                         PAYER_ID INT NULL,
                         PAY_CCY_ID INT NOT NULL,
                         PAY_AMOUNT NUMERIC(8, 2) NOT NULL,
                         PAY_TIME TIMESTAMP NOT NULL,
                         CREATE_TIME TIMESTAMP NOT NULL,
                         FOREIGN KEY (PAY_CCY_ID) REFERENCES CURRENCY(ID)
);

INSERT INTO CURRENCY (CCY_CD) VALUES('N/A');
INSERT INTO CURRENCY (CCY_CD) VALUES('USD');
INSERT INTO CURRENCY (CCY_CD) VALUES('CAD');
INSERT INTO CURRENCY (CCY_CD) VALUES('GBP');
INSERT INTO PAYER (NAME) VALUES ('UNKNOWN');
INSERT INTO PAYER (NAME) VALUES ('JACK');
COMMIT;
